// =====================================================================
// CHANGE PASSWORD PAGE — "/change-password". Mandatory first-login gate
// for any account whose password was generated by the system rather
// than chosen by the alumnus (the Alumni Tracer Survey's matched-account
// path, or an admin approving a Pending submission — see
// supabase/alumni_tracer_intake.sql and PublicTracerSurveyPage.tsx).
// App.tsx's ProtectedRoute redirects here whenever
// profiles.must_change_password is true and won't let the person past
// it to any dashboard until this clears it.
//
// Distinct from ResetPasswordPage.tsx (the "I forgot my password" email
// link flow) — this one runs for an already-signed-in session, not a
// one-time recovery token.
// =====================================================================
import React, { useState } from 'react';
import { useNavigate } from 'react-router';
import { useAuth } from './AuthContext';
import { supabase } from '../../lib/supabaseClient';
import { KeyRound, LogOut } from 'lucide-react';
import { NAVY, PANEL_GRADIENT, PasswordStrengthField, InputField, isPasswordStrong } from './AuthPage';
import asianCollegeLogo from '../../imports/asiancollege_logo.jpeg';

export default function ChangePasswordPage() {
  const { user, loading, logout, refreshProfile } = useAuth();
  const navigate = useNavigate();

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  React.useEffect(() => {
    if (!loading && !user) navigate('/login', { replace: true });
    // Already changed (e.g. re-visiting this URL directly) — nothing left to do.
    if (!loading && user && !user.mustChangePassword) {
      const dest = user.role === 'admin' ? '/admin' : user.role === 'faculty' ? '/user' : `/${user.role}`;
      navigate(dest, { replace: true });
    }
  }, [loading, user, navigate]);

  const handleLogout = () => { logout(); navigate('/login'); };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    if (!isPasswordStrong(password)) {
      setError('Password must be at least 8 characters and include an uppercase letter, a lowercase letter, a number, and a special character.');
      return;
    }
    if (password !== confirm) {
      setError('Passwords do not match.');
      return;
    }
    if (!user) return;
    setSubmitting(true);
    const { error: updateErr } = await supabase.auth.updateUser({ password });
    if (updateErr) {
      setSubmitting(false);
      setError('Could not update your password. Please try again.');
      return;
    }
    const { error: profileErr } = await supabase.from('profiles').update({ must_change_password: false }).eq('id', user.id);
    if (profileErr) {
      setSubmitting(false);
      setError('Your password was updated, but we could not finish setting up your account. Please contact the Alumni Office.');
      return;
    }
    const { ok } = await refreshProfile();
    setSubmitting(false);
    if (!ok) { setError('Password updated — please sign in again.'); return; }
    const dest = user.role === 'admin' ? '/admin' : user.role === 'faculty' ? '/user' : `/${user.role}`;
    navigate(dest, { replace: true });
  };

  if (loading || !user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-gray-400 text-sm">Loading…</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4" style={{ background: '#f0f4f8' }}>
      <div className="w-full max-w-sm bg-white rounded-2xl shadow-2xl p-8">
        <img src={asianCollegeLogo} alt="Asian College" className="h-12 w-auto object-contain mx-auto mb-5" />
        <div className="flex flex-col items-center text-center mb-5">
          <div className="w-12 h-12 rounded-full flex items-center justify-center mb-3" style={{ background: PANEL_GRADIENT }}>
            <KeyRound className="w-6 h-6 text-white" />
          </div>
          <h2 className="text-xl font-bold" style={{ color: NAVY }}>Set Your Password</h2>
          <p className="text-xs text-gray-400 mt-1.5 leading-relaxed">
            Welcome, {user.name.split(' ')[0]}! For security, please choose your own password before continuing.
          </p>
        </div>

        {error && (
          <div className="mb-3 px-3 py-2 bg-red-50 border border-red-200 rounded-md text-xs text-red-600">{error}</div>
        )}

        <form onSubmit={handleSubmit} className="space-y-3">
          <PasswordStrengthField value={password} onChange={setPassword} required />
          <InputField placeholder="Confirm Password" type="password" value={confirm} onChange={setConfirm} required />
          <button type="submit" disabled={submitting}
            className="w-full py-2.5 mt-1 text-sm font-bold text-white rounded-full transition-all hover:opacity-90 disabled:opacity-60"
            style={{ background: PANEL_GRADIENT }}>
            {submitting ? 'SAVING…' : 'SAVE & CONTINUE'}
          </button>
        </form>

        <button onClick={handleLogout} className="w-full flex items-center justify-center gap-1.5 text-xs text-gray-400 hover:text-gray-600 mt-4">
          <LogOut className="w-3.5 h-3.5" /> Sign out
        </button>
      </div>
    </div>
  );
}
